#POST http://localhost:8080/images/upload
#Content-Type: multipart/form-data; boundary=WebAppBoundary
#
#--WebAppBoundary
#Content-Disposition: form-data; name="field-name"; filename="file.txt"
#
#< ./relative/path/to/local_file.txt
#--WebAppBoundary--

###
GET http://localhost:8080/posts/get
